### PR TITLE
show more errors to the end user

### PR DESCRIPTION
**Pull request by elharo**
@patflynn @loosebazooka This is a possible way to address this issue. For now this is incomplete and just for discussion. That is, does this general approach make sense?

### CODE REVIEW

**Comment by patflynn** [comment]
It seems like the debugger should be listening for login status change using the GoogleLoginListener and disabling itself upon logout.

**Comment by elharo** [comment]
What would this mean in UI terms? Disable the launch configurations that
use the cloud debugger?

Also, what if the user logs out while a cloud debugger session is open? Do
we close the frame?






On Wed, Dec 9, 2015 at 3:29 PM, Patrick Flynn <notifications@github.com>
wrote:

> It seems like the debugger should be listening for login status change
> using the GoogleLoginListener and disabling itself upon logout.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-intellij/pull/306#issuecomment-163383260>
> .
>



-- 
Elliotte Rusty Harold
elharo@macfaq.com

**Comment by patflynn** [comment]
I don't think that you need to disable the launch configs. You just will
see the login widget when your prompted to select a project on launch.

An open cloud debug sessions should definitely be closed (with a prompt)
upon logout.

**Comment by elharo** [comment]
On Wed, Dec 9, 2015 at 4:03 PM, Patrick Flynn <notifications@github.com>
wrote:

>
> An open cloud debug sessions should definitely be closed (with a prompt)
> upon logout.
>

Closing open cloud debug sessions seems to risk losing data. I.e. the user
has received snapshots and may not want them to just disappear.


-- 
Elliotte Rusty Harold
elharo@macfaq.com

**Comment by patflynn** [comment]
That's not great, but not awful considering the user has to explicitly
logout to trigger it.

The alternative is to introduce a disconnected state to the debugger
session, so that the session is clearly disconnected, but still available
to view. (I fear that would mean undoing the work we did earlier to remove
the red x)

**Pull request closed without merging**
