### PR TITLE
Stop app confirmation messaging

### LINKED ISSUE #598: Stopping recent Flex deployment dialog should provide more information about what is being stopped.
At the moment it just says 'are you sure you want to stop this application'.  I believe 'application' matches to 'project' in App Engine speak, when we're really just stopping a specific version. We may want to include a link to more docs here too.

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #598 

image

Links to: https://cloud.google.com/appengine/docs/java/console/#versions

### CODE REVIEW

**Comment by etanshaul** [comment]
Updated wording:

image

**Comment by patflynn** [comment]
Seems weird to have capitalized 'Cloud Platform Console' without the
'Google'.

**Comment by etanshaul** [comment]
That is how they have it in the documentation I am linking too - I was trying to keep it consistent with that. We can add 'Google' to ours though.

**Comment by patflynn** [comment]
LGTM

**Pull request merged**
