### PR TITLE
Expand plugin description

### PR DESCRIPTION
**Pull request by elharo**
@patflynn I expanded the description that IDEA shows in the plugins window to explain what the core plugin does. Feel free to suggest alternate language if you don't like the exact phrasing.

### CODE REVIEW

**Comment by loosebazooka** [comment]
this branch appears to have some of your code from another branch (remove red x)

**Comment by elharo** [comment]
fixed

**Comment by patflynn** [comment]
Technically it doesn't provide deployment as of yet.  

Also the PR title should be a bit more descriptive.

**Comment by elharo** [comment]
done

**Comment by patflynn** [comment]
Let's leave out all the app engine references for now.  Just cloud repos and debugger.

**Comment by elharo** [comment]
The inspections are AppEngine specific, right? How about

Debug Java applications running in the Google cloud from inside IDEA.
Code inspections for AppEngine Java code.

**Comment by patflynn** [comment]
LGTM

**Pull request merged**
