### PR TITLE
Show project name in mvm deploy dialog

### LINKED ISSUE #476: Default Managed VM Cloud name to include project name
When creating a Managed VM cloud config it should include the selected project's name in the title by default.  This will help the user identify which project he's targeting during deployment.

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #476

### CODE REVIEW

**Comment by patflynn** [comment]
Is there no way to change the actual cloud name?  The user can edit it, so I was hoping we could set it to default to the project name.

**Comment by etanshaul** [comment]
by cloud name, you mean the name of the element in the "Server:" dropdown? In the screenshot below its "Cloud 1", so you're asking if this could be something like "Cloud 1 - MyProject"?

image

**Comment by patflynn** [comment]
yeah.

**Comment by etanshaul** [comment]
I checked on both ends for any ability to customize the name: at the point of creating the cloud server, and at the point of displaying in the deployment window. It doesn't look like there's a way to do this. I can discuss details if interested - basically run through the web of framework code.

**Comment by etanshaul** [comment]
Updated look:

image

**Comment by patflynn** [comment]
I like it, although I'm not loving the hyphen. It looks kind of weird in
the context of the rest of the border being blue.

**Comment by etanshaul** [comment]
Looks ok to me with a colon. Here's one more look at it (better margins too to make it less cramped):

image

**Comment by patflynn** [comment]
What happens if I click to edit the cloud config from this UI and change
the project?

**Comment by etanshaul** [comment]
fixed. used the google commons EventBus to publish/subscribe to project name changes in the configuration so that we can update the UI appropriately.

**Comment by patflynn** [comment]
I'm not sure that the event bus is the right ool for this. But we can look into patterns for handling this later. LGTM

**Pull request merged**
