### PR TITLE
Update our IDEA SDK to 15.0.2 to match Android Studio

### PR DESCRIPTION
**Pull request by patflynn**

### CODE REVIEW

**Comment by elharo** [comment]
We might want to wait on this. Android studio has been having some troubles with the latest release.

**Comment by patflynn** [comment]
Have they reverted back from 15.0.2?

**Comment by patflynn** [comment]
@elharo  Looking at the Android Studio thread it looks like they're moving forward with 15.0.2.

**Comment by elharo** [comment]
lgtm then

**Pull request merged**
