### PR TITLE
Update copyright header template

### LINKED ISSUE #712: incorrect copyright header
We should be using the Google copyright header for new files in this project and not the AOSP copyright header.

s/
Copyright (C) 2016 The Android Open Source Project
/
Copyright 2016 Google Inc. All Rights Reserved.
/

### PR DESCRIPTION
**Pull request by chanseokoh**
In relation to #712.

- `.idea/copyright/Android_Copyright.xml` renamed to `.idea/copyright/Google_Copyright.xml`
- `.idea/copyright/profiles_settings.xml`

### CODE REVIEW

**Comment by etanshaul** [comment]
lgtm. but you may want to confirm that we are ok changing copyrights on files that previously had the old version (rather than just for new files going forward). I don't see why not, but IANAL

**Comment by chanseokoh** [comment]
Right, I also thought that's the usual way of updating copyrights. I expect to update this PR accordingly. @patflynn will say something.

**Comment by patflynn** [comment]
for now let's just update the template so new files have the right one.

**Comment by chanseokoh** [comment]
You mean updating only `Google_copyright.xml` and `profiles_settings.xml` and leaving the current copyright headers intact?

**Comment by chanseokoh** [comment]
Updating only the template and the IDE setting. We can think later about what to do with the existing headers.

**Comment by etanshaul** [comment]
lgtm

**Comment by patflynn** [comment]
:shipit:

**Pull request merged**
