### PR TITLE
standardize on term snapshot location for user messages

### PR DESCRIPTION
**Pull request by elharo**
@patflynn

### CODE REVIEW

**Comment by akerekes** [comment]
Shouldn't we also change the message keys to use snapshot instead of breakpoint? E.g.: https://github.com/GoogleCloudPlatform/gcloud-intellij/blob/messages/google-cloud-tools-plugin/resources/messages/CloudToolsBundle.properties#L99

**Comment by elharo** [comment]
No, they're not user visible and various classes in the IDEA codebase we inheit from use the word "breakpoint"

**Comment by elharo** [comment]
ping

**Comment by patflynn** [comment]
LGTM

**Pull request merged**
