### PR TITLE
Transition to idea15

### PR DESCRIPTION
**Pull request by loosebazooka**
Preliminary, compiles and tests seem to pass.

### CODE REVIEW

**Comment by loosebazooka** [comment]
@elharo @patflynn Take a look, I didn't much deep testing here, but I think is what we need.

Did not manually run through all our features
Have not yet checked if this is still compatible with idea14

**Comment by loosebazooka** [comment]
more notes : 

Is NOT compatible with idea14.

**Comment by patflynn** [comment]
Does our Cloud Repo feature in Android Studio master still work?

**Comment by patflynn** [comment]
LGTM

**Pull request merged**
