### PR TITLE
Restructure metrics event actions

### PR DESCRIPTION
**Pull request by chanseokoh**
It makes more sense to me to alter the current event structure.

Basically, I'm enforcing my rule that the second parameter to `trackEvent()` are event actions.

### CODE REVIEW

**Comment by patflynn** [comment]
Is the purpose of this to make 'eventLabel' purely for qualifying an action with some extra dimension?

**Comment by chanseokoh** [comment]
Yes, that's my intention. 'eventAction' is a concrete action that we want to track. 'eventLabel' and 'eventValue' is some extra metadata info (key-value pair).

**Comment by chanseokoh** [comment]
Of course, we can reconsider the design from the ground.

**Comment by patflynn** [comment]
No I think this is reasonable.

LGTM

**Pull request merged**
