### PR TITLE
Remove no longer applicable flexible environment messaging from Cloud…

### LINKED ISSUE #773: Remove app engine flexible price warning from cloud settings
On the Cloud configuration page (Settings -> Clouds) it is no longer appropriate to have the app engine flexible price warning here because we now also support deployment to app engine standard. We also have a price warning in the Deployment UI so we should be covered.

image

### PR DESCRIPTION
**Pull request by etanshaul**
… panel

fixes #773

### CODE REVIEW

**Comment by patflynn** [comment]
LGTM

**Comment by patflynn** [comment]
I wonder if we could send them to the global App Engine docs?

**Comment by etanshaul** [comment]
Which docs are these?

**Comment by etanshaul** [comment]
Oh I misread your comment. Yea that would be nice. I'll replace the flex warning with this.

**Comment by etanshaul** [comment]
I took your suggestion - it now points to the AE docs instead.

**Comment by etanshaul** [comment]
image

**Comment by patflynn** [comment]
LGTM

**Pull request merged**
