### PR TITLE
Fixes to App Engine product naming

### PR DESCRIPTION
**Pull request by devlance**
This brings the plugin in line with the Google usage of the naming so there isn't a discrepancy.

### CODE REVIEW

**Comment by patflynn** [comment]
LGTM.

it doesn't appear likely that your changes caused the errors CI is seeing. Will file an issue.

**Comment by etanshaul** [comment]
This PR actually causes legitimate unit test failures in `AppEngineDeploymentRunConfigurationEditorTest`.

The memory leak errors are a side effect we can investigate separately.

**Comment by patflynn** [comment]
aha. Yeah I see it now.  @devlance there's a label message check in the test.

Thanks Etan.

**Comment by devlance** [comment]
Updated the unit tests.

**Comment by patflynn** [comment]
Thanks Brett!

**Pull request merged**
