### PR TITLE
Write to UI from the UI thread

### LINKED ISSUE #622: Error report of a crash in our login plugin
Original Description (lang: ):
Access is allowed from event dispatch thread only.
Submitted by: <anonymous>
Submitted on: 2016-04-12 04:33 UTC
Product Version: 2016.1.1
Package Name: com.google.gct.idea
Package Version Name: 2016.1.1
Device Model: unknown
Bugs (0)
Crash Data
Exception class name: com.intellij.diagnostic.LogMessageEx$1
Exception message: Access is allowed from event dispatch thread only.
Stack trace:
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@1b4c123 Current thread: Thread[ApplicationImpl pooled thread 136,4,main] 2829317 SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.1.1#IC-145.597.3 IDEA, eap:false, os:Windows 10 10.0, java-version:Oracle Corporation 1.8.0_60-b27,6,main] 32562073

java.lang.Throwable
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:501)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:29)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1115)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1099)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1091)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.assertDispatchThread(FocusManagerImpl.java:1200)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.isFocusTransferReady(FocusManagerImpl.java:680)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.isFocusBeingTransferred(FocusManagerImpl.java:1153)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.isFocusBeingTransferred(IdeFocusManagerImpl.java:144)
	at com.intellij.ide.impl.DataManagerImpl.getFocusedComponent(DataManagerImpl.java:253)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:207)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.<init>(DialogWrapperPeerImpl.java:100)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerFactoryImpl.createPeer(DialogWrapperPeerFactoryImpl.java:37)
	at com.intellij.openapi.ui.DialogWrapper.createPeer(DialogWrapper.java:819)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:216)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:212)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:257)
	at com.intellij.openapi.ui.Messages$MessageDialog.<init>(Messages.java:1343)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:271)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:284)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:295)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:725)
	at com.google.cloud.tools.intellij.login.IntellijGoogleLoginService$AndroidUiFacade.showErrorDialog(IntellijGoogleLoginService.java:457)
	at com.google.gdt.eclipse.login.common.GoogleLoginState.logInWithLocalServer(GoogleLoginState.java:352)
	at com.google.cloud.tools.intellij.login.IntellijGoogleLoginService$1.run(IntellijGoogleLoginService.java:191)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Throw file name: LogMessageEx.java
Throw line number: 111
Throw class name: com.intellij.diagnostic.LogMessageEx
Throw method name: createEvent
Package Information
Package name: com.google.gct.idea
Process name: Cloud Tools for IntelliJ
Package version name: 2016.1.1
Installer package name: Cloud Tools for IntelliJ
Build
Product: Cloud Tools for IntelliJ
Model name: unknown
Device: unknown
Build ID: 2016.1.1
Build Type: unknown
Release: 2016.1.1

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #622

### CODE REVIEW

**Comment by patflynn** [comment]
That was quick! Thanks!

:ship:

**Comment by chanseokoh** [comment]
LGTM

**Comment by patflynn** [comment]
This fix belongs in the Android Studio code as well.

**Comment by etanshaul** [comment]
I'll create a pr for AS as well.

**Pull request merged**
