### PR TITLE
in the cloud attach dialog, putting the version text in parentheses

### LINKED ISSUE #419: Make module / target / version copy in cloud attach dialog clearer
See PR #418 for the discussion about this

### PR DESCRIPTION
**Pull request by etanshaul**
…pending state

Fixes #419 

image

Leaving the selector label as Target for now.

### CODE REVIEW

**Comment by patflynn** [comment]
LGTM

**Comment by elharo** [comment]
Is it possible to include the necessary change to tutorial.markdown at the same time? It mayb e tricky since it's on a different branch; and if so I'm will to take that as a separate PR. However we should probably ge tin the habit of updating docs in sync with code changes.

**Comment by etanshaul** [comment]
@elharo, I already had the other PR ready to go so this time around I am merging them separately. Going forward though I agree it would be nice to merge code + doc changes together in a single PR, perhaps using a fork (although I still think that would require us to select a specific branch for the PR).

**Comment by etanshaul** [comment]
@elharo if it looks good to you, I'll go ahead and merge it in

**Comment by elharo** [comment]
lgtm

**Pull request merged**
