### PR TITLE
disable findbugs missing equals override

### LINKED ISSUE #512: Disable pmd force override equals, hashcode
Currently PMD forces us to override equals and hashcode even if we don't want to modify the behavior of the superclass. It suggests to have a stub override that just calls super. (Whats worse is that if you follow its suggestion it then complains that you are overriding a method that does nothing but call super). We should disable this PMD check altogether.

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #512

### CODE REVIEW

**Comment by etanshaul** [comment]
@patflynn @chanseokoh ptal

**Comment by chanseokoh** [comment]
I can tell at least it is the right place to disable the warning globally.

**Comment by etanshaul** [comment]
cool, so lgtmty? (looks good to me, to you?)

**Comment by chanseokoh** [comment]
LGTM

**Comment by patflynn** [comment]
LGTM

**Pull request merged**
