### PR TITLE
Rename core-plugin -> google-cloud-tools

### LINKED ISSUE #357: remove .idea folders from sub-projects
I don't think core-plugin/.idea and google-account-plugin/.idea have any use anymore.

### PR DESCRIPTION
**Pull request by loosebazooka**
also remove unnecessary .idea directory in sub-projects

closes #357 #354

### CODE REVIEW

**Comment by loosebazooka** [comment]
@patflynn @elharo

**Comment by loosebazooka** [comment]
this is probably going to disrupt everyone's dev, we'll have to make sure everyone rebases against this when it goes in

**Comment by patflynn** [comment]
google-cloud-tools-**plugin**?

**Comment by loosebazooka** [comment]
Didn't we vote against this? I guess it makes sense for the purpose of gradle project naming though.

**Comment by loosebazooka** [comment]
PTAL

**Comment by patflynn** [comment]
LGTM

**Comment by elharo** [comment]
Please assign yourself to the two bugs this addresses, and not their numbers here. Now that the team is growing it's going to be more important to keep track of this to avoid duplicate work.

**Pull request merged**
