### PR TITLE
update attach dialog image to match latest version

### PR DESCRIPTION
**Pull request by etanshaul**
"Module" was changed  to "Target"
and a "Default" copy was prepended to default module versions.

Updating the image to reflect these changes

### CODE REVIEW

**Comment by patflynn** [comment]
Is it me or does it look like it's saying 'default version', as in
'default' applies to 'version'.

**Comment by etanshaul** [comment]
No, I agree now that you point it out. 

Adding a comma may be clearer: "Default, Version: 123".

**Comment by etanshaul** [comment]
Or better yet:

"Default (Version: 123)".

**Comment by patflynn** [comment]
Should we identify 'Default' as module name? e.g. "Module: Default,
Version: 123"?

**Comment by patflynn** [comment]
That is better.

**Comment by etanshaul** [comment]
Maybe it is confusing actually to call it Target instead of Module. Just for comparison (with the proposed update):

Target   |  Default (Version: 123)
Module  |  Default (Version: 123)

I think the second one is clearer, especially since they actually called modules in the Web UI and all the documentation. I think it may make sense to revert to using the word Module instead of Target.

**Comment by etanshaul** [comment]
see #424. Depending on the outcome of that PR, the screenshot may need to be redone again.

**Comment by elharo** [comment]
I suggest we merge this one in since it's closer and ready to go. LGTM.

**Comment by etanshaul** [comment]
Closing - migrated to #425

**Pull request closed without merging**
