### PR TITLE
cloud config edit dialog width fix

### LINKED ISSUE #591: Cloud settings edit menu needs to be enlarged
image

To get here: 
1) Create new Flex Env cloud.
2) In the App Servers menu, right click on the cloud and select 'Edit Configuration'

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #591 

(pending cross platform test)

### CODE REVIEW

**Comment by etanshaul** [comment]
confirmed in linux and osx. the min width setting was causing the dialog to "shrink" when viewed in edit mode.

**Comment by patflynn** [comment]
screenshot?
:eyes:

**Comment by etanshaul** [comment]
This is how the edit menu opens up now by default (note that the color issue will be dealt with by #594):

screen shot 2016-04-06 at 12 22 07 pm

**Comment by patflynn** [comment]
:shipit:

**Pull request merged**
