### PR TITLE
Make inner classes static as suggested by FindBugs

### PR DESCRIPTION
**Pull request by chanseokoh**
This pull request addresses one of FindBugs issues: SIC_INNER_SHOULD_BE_STATIC. Inner classes do not use the embedded reference to their outer classes, so no need to be non-static. A test case is also fixed according to the these changes.

Note: I am learning Java and Java practices now. I am also trying to familiarize myself with the GitHub workflow for making contributions to this repo by addressing issues reported by FindBugs. Any kind of feedback is more than welcome.

### CODE REVIEW

**Comment by elharo** [comment]
squash commits; then LGTM

**Comment by patflynn** [comment]
Yup. Feel free to commit after you've squashed.  If you don't know what 'squashing' is let me know. I'll walk you through it.

**Comment by chanseokoh** [comment]
I am looking at some docs for squashing. It just feels a bit dangerous as they tell to use 'rebase' and a '--force' option.

**Comment by chanseokoh** [comment]
#241

**Comment by patflynn** [comment]
It's only on your branch so should not be an issue.  There's no danger that
you can mess with the project's history as the master is protected.

**Comment by elharo** [comment]
Per squashing see http://cafe.elharo.com/source-code-control/how-to-squash-git-commits/ or ask someone on the team for help.

**Pull request merged**
