### PR TITLE
Install pre push hook

### PR DESCRIPTION
**Pull request by patflynn**
related to #709 

Just an example.  Not sure I want to force this.  Having to wait minutes to push ended up being annoying.

### CODE REVIEW

**Comment by etanshaul** [comment]
Agree that it might be annoying to wait. Just taking a step back - if the check fails up in travis then we do get notified by email. That's sort of one of the reasons travis is there for - to be a line of defense for our master branch. I wonder if we really need this extra step?

**Comment by patflynn** [comment]
The idea is that running locally is a fair bit faster then waiting to find
out you forget to optimize imports by travis.

This change doesn't force anybody to use it.

**Comment by chanseokoh** [comment]
One problem I see is not restoring the stash when one cancels the check in the middle (Ctrl+C).

**Comment by etanshaul** [comment]
We should be able to catch the sigint using a [trap](http://linuxcommand.org/wss0160.php).

**Comment by patflynn** [comment]
Without objection I'm just going to merge this so people can use it for reference (if they want to).  Feel free to add a sigint trap to make it more robust.

**Comment by etanshaul** [comment]
cool with me. lgtm

**Pull request merged**
