### PR TITLE
subclass teardown behavior should occur prior to calling the superclass

### PR DESCRIPTION
**Pull request by patflynn**
I suspect this will fix the memory issue exception

possibly fixes: #861

### CODE REVIEW

**Comment by etanshaul** [comment]
This doesn't make this pr invalid, but I did try this and the memory leak error did not go away from what I can remember. To reproduce, keep this change, and reintroduce the unit test failure from that other PR (by changing the localized variable test).

**Comment by etanshaul** [comment]
lgtm because I think this is correct regardless of my last poitn

**Comment by patflynn** [comment]
ah I see.  This exception happens regardless of whether the test passes or fails.

**Comment by etanshaul** [comment]
I only see the leak on test failure. I'm running the test like this:

`./gradlew -Dtest.single=AppEngineDeploymentRunConfigurationEditorTest :google-cloud-tools-plugin:test`

**Comment by patflynn** [comment]
I'm running from the IJ console and see the output on both success and
failure. Perhaps the gradle test task produces more output on failure.

**Pull request merged**
