### PR TITLE
update missing copyrights

### PR DESCRIPTION
**Pull request by patflynn**

### CODE REVIEW

**Comment by patflynn** [comment]
crap, it should be 2016.

**Comment by patflynn** [comment]
fixed.

**Comment by etanshaul** [comment]
`findbugs-excludefilter.xml `has its copyright after the opening tag. Was this on purpose?

**Comment by patflynn** [comment]
you mean after the  <?xml version="1.0" encoding="UTF-8"?>? I think that's
standard for XML.

**Comment by etanshaul** [comment]
Yea you're right, the type declaration has to come first for it to be well formed.

lgtm

**Pull request merged**
