### PR TITLE
Suppress checkstyle javadoc trailing period check

### PR DESCRIPTION
**Pull request by etanshaul**
Removing the checkstyle check that forces you to have a period at the end of the first sentence of a javadoc. Usually this is ok, but for things like the following it just gets in the way:

```
/**
 * @author user
 */

```

@aslo  ptal

### CODE REVIEW

**Comment by aslo** [comment]
LGTM!

**Comment by patflynn** [comment]
not sure about this change. I don't think the example is valid Google style. All public class and interfaces require javadoc including a descriptive comment.

**Comment by etanshaul** [comment]
@patflynn - all of the code we integrated from the old plugin has author attribution in the source files like the example I showed. I didn't want to have to update them all with a trailing period just to pass checkstyle. But maybe because its now part of our plugin it makes sense to do so.

**Comment by elharo** [comment]
Wow. This checkstyle check may be actively wrong. It's extremely pedantic, but the official rule is no period unless  there's a following sentence i.e. 

@author user

but

@author user. This person is really cool.

**Comment by etanshaul** [comment]
That makes sense. I think that the rules just aren't granular enough to distinguish between a full sentence that would need a period and an author annotation with just a name as in your first example.

**Pull request merged**
