### PR TITLE
Add more stacktrace output to console in travis build

### PR DESCRIPTION
**Pull request by patflynn**

### CODE REVIEW

**Comment by etanshaul** [comment]
Does this not add an extra check execution to the build? LGTM otherwise

**Comment by etanshaul** [comment]
Oh, is the check implied before this change?

**Comment by patflynn** [comment]
yeah. My understanding is that if you don't include the "script" element
it'll detect gradle and automatically call ./gradlew check.  This change
makes it explicit and adds the ''--stacktrace" flag.

**Comment by etanshaul** [comment]
ok. 🚢

**Comment by patflynn** [comment]
It looks like you might be right that this is related to having multiple concurrent builds:
https://discuss.gradle.org/t/gradle-check-fails-but-tests-finish-with-success/10214/5

**Comment by etanshaul** [comment]
Good find. I'd hate to reduce the concurrency given how slow things are as is. But if we have no other choice we can try it.

**Comment by etanshaul** [comment]
And why this tends to happen on the 'pr' build and not the 'push' build is totally perplexing to me.

**Comment by patflynn** [comment]
Maybe one gets pre-empted by the other..

**Pull request merged**
