### PR TITLE
Fix deployment config validation order

### LINKED ISSUE #679: Deployment settings are lost permanently when changing a deployment source and clicking 'Apply' or 'Ok'
Steps to reproduce:

1. Create a deploy configuration. Provide some valid settings, and close the config window.
2. Open the config window again.
3. Change a deployment source (e.g., from Maven source to file system source).
 - At this point, all settings will be reset. However, if we click 'Cancel', they values will be restored when we open the config window later.
4. Click 'Ok' or 'Apply'. This will trigger validation error. Click 'Cancel' to close the window.
5. Open the window again. Deployment source selection has been changed, and all the settings are lost.

### PR DESCRIPTION
**Pull request by etanshaul**
fixes #679 

Performs validation before saving the settings.

Note that doesn't affect the state of the deployment source when clicking 'ok' / 'apply' with a validation error. This only affects the portion of the deployment config where an extension point is provided, e.g. everything other than the name, server, and deployment.

### CODE REVIEW

**Comment by chanseokoh** [comment]
LGTM. I pushed the 'Merge pull request' button and broke the CLA requirement. I don't understand this CLA business.

**Comment by chanseokoh** [comment]
Hmm... so I see it's not possible to revert back the deployment source with the steps in #679. This is quite tricky indeed.

**Comment by etanshaul** [comment]
We should probably stick with the pattern of having the person who created the PR do the merging - I don't know if that confused the cla bot.

**Comment by chanseokoh** [comment]
Ah, to be correct, I pushed the 'Update branch' button, not the 'Merge the branch'.

**Comment by etanshaul** [comment]
Oh interesting. No worries. I'll do a dummy commit if necessary after travis finishes.

**Comment by etanshaul** [comment]
closing in attempt to fix stuck pre-merge check

**Pull request closed without merging**
